name: Tmate SSH (Free - No Keys Needed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        # limit-access-to-actor wali line yahan se hata di hai
